---
abstract: 'Dancer adapter for Log::Log4perl'
author:
  - 'Flavio Poletti <polettix@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.102400'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Logger-Log4perl
requires:
  Dancer: 1.2003
  perl: 5.008_000
version: 0.7.0_03
